### ISSUE TITLE
Absence of eQTLs for some genes

### ISSUE THREAD

**Issue by gprashant17** [randel/MixRF#3]
Few genes in my dataset do not have eQTLs. The eqtl.lis argument (of MixRF.impute) maps these genes to an empty character array. However, I am unable to run the MixRF.impute command with these arguments and this error shows up:

> Error in { : task 1 failed - "subscript out of bounds"

Should all the genes in eqtl.lis must have at least one associated eQTL (SNP ID)? Otherwise, is there any other way to represent the absence of eQTLs in these genes?

Thanks in advance.

**Comment by randel** [comment]
Thanks for reporting this! The simplest workaround may be: 
1) replace the elements of `eqtl.lis` for genes without eQTLs with a fake intercept term, say `intercept`; 
2) add a column of 1 with name `intercept` to `snp.dat`.

**Comment by gprashant17** [comment]
By adding a column of 1, do you mean that all the elements of the column `intercept` in snp.dat should be 1?

**Comment by randel** [comment]
Yes, this would not introduce new information but get rid of the error message.

**Comment by gprashant123** [comment]
Thanks, I added a new column  and filled the empty values as "intercept", as you mentioned, but I still get this error:

> Error in { : task 1 failed - "non-numeric argument to binary operator"

The dimensions of my data are 175 x 4812 x 4 and the eqtl.lis is a list of length 4812, and the value of each of them is a character array containing SNP IDs (as given in the protected data of GTEx). The matrix snp.dat has dimensions 175 x 600430. 

I am not sure why it works perfectly for the simulated dataset given in the package but it shows this error in mine.

My guess is it stops somewhere in the code snippet shown below, and the function MixRF.impute.single is not invoked:

`ls <- foreach(i=1:g) %dopar% {
    MixRF.impute.single(Yi=Ydat[,i,], eqtl.lis.i=eqtl.lis[[i]], snp.dat, cov=cov,
                        iPC.cov=iPC.cov)}`

**Comment by gprashant17** [comment]
It works now, but it takes plenty of time if there are more number of genes. The dimensions of my dataset is 175 x 4812 x 4 and it never completes. Is this usual?

**Comment by randel** [comment]
As stated in the paper, we suggest parallel computation. Based on the following statement from the paper, I guess you may need to run about 24 hours for your data using a single node. You can get a more accurate estimate of the time by imputing a single gene (say t1) and the total time estimate is t1 x 4812.

> With parallel computing, imputing **10,000 genes** in **9 tissue types** from about 150 individuals and obtaining the **10-fold** CV-based measures of imputation quality could be completed within **30 hr with a 40-node cluster** (3.0 GHz Intel Xeon E7 processor) and 16.5 GB of memory.
