### ISSUE TITLE
possible to have a demo showing input format of GTEx data?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [randel/MixRF#5]
possible to have a demo showing input format of GTEx data?

**Comment by randel** [comment]
Here is an example of input data in the package.
https://rdrr.io/cran/MixRF/man/sim.html

After installing and loading the package, one can try `data(sim)`.
https://github.com/randel/MixRF/tree/master/data

**Comment by yezhengli-Mr9** [comment]
Get it. As a note:
it takes me about two hours to get estimation for 482 genes with 6 tissues by a 13-inch MacBook Pro.

**Comment by yezhengli-Mr9** [comment]
A note:
Three hours for 25 genes with 10 tissues by a (stronger?) server (IBM bash node).

**Comment by yezhengli-Mr9** [comment]
About Six hours and twenty minutes for 85 genes with 10 tissues by one IBM bash node. 
However, seven and half hours for 52 genes with 10 tissues by one IBM bash node (while the latter case should be faster, IBM bash nodes might have different performance in the backend).

**Comment by yezhengli-Mr9** [comment]
About twelve hours for 25 genes with 20 tissues with one IBM bash node.
