### ISSUE TITLE
For correlation=TRUE

### ISSUE THREAD

**Issue by yezhengli-Mr9** [randel/MixRF#6]
For `correlation=TRUE`, I always confront the following issue:
```
Calls: MixRF.impute -> get.CVlist -> sample -> sample.int
In addition: Warning messages:
1: In split.default(sample(av.samp), 1:nCV) :
  data length is not a multiple of split variable
2: In split.default(sample(av.samp), 1:nCV) :
  data length is not a multiple of split variable
```
For example, in case setting number of patients=600, number of tissues = 6 (default nCV or nCV = 3).

**Comment by randel** [comment]
The idea is to use cross-validation to estimate the correlation. `get.CVlist()` will split the data into nCV fold and return the list of CV samples. `av.samp` is the available sample index with observations, and this depends on your data, not only the number of patients/tissues. When the length of `av.samp` cannot evenly be divided by `nCV`. `split()` will throw a warning, but this only means that the sample split is not even, and only differs by one, which is unavoidable.

**Comment by yezhengli-Mr9** [comment]
> The idea is to use cross-validation to estimate the correlation. `get.CVlist()` will split the data into nCV fold and return the list of CV samples. `av.samp` is the available sample index with observations, and this depends on your data, not only the number of patients/tissues. When the length of `av.samp` cannot evenly be divided by `nCV`. `split()` will throw a warning, but this only means that the sample split is not even, and only differs by one, which is unavoidable.


Hi Jiebiao, 
Thanks for your fast and detailed response~

Is it easier to debug it on your end to make it more adaptive? I hope `only differs by one` do not have to throw error. I am indeed not an R expert and after dozens' of hours of failure (I should initially try cross-validation on baby dataset first), I might start debugging this issue next week.

Comparatively, for fitted result, I used to run even 12-24 hours and never confront any problem.

Best,
Yezheng

**Comment by randel** [comment]
My understanding is that this is just a warning, not an error. It would not affect the results other than the uneven splitting of available samples in cross-validation. If you do encounter an error, please share a reproducible code example.
